import os
import sys
import time
import requests
import io
import wave
import struct

# Default test targets
API_BASE_URL = os.getenv("API_BASE_URL", "http://localhost:8000")
API_KEY = os.getenv("API_KEY", "default_secure_api_key_change_in_production")


def create_sample_wav_bytes(duration_seconds: float = 2.0, sample_rate: int = 24000) -> bytes:
    """Generate a clean synthetic sine wave WAV file in memory for testing."""
    num_samples = int(duration_seconds * sample_rate)
    wav_io = io.BytesIO()
    with wave.open(wav_io, 'wb') as wav_file:
        wav_file.setnchannels(1)  # Mono
        wav_file.setsampwidth(2)  # 16-bit
        wav_file.setframerate(sample_rate)
        
        for i in range(num_samples):
            # 440 Hz tone (A4)
            value = int(16000 * (0.5 * (1.0 + (i / num_samples))) * (i % 55 < 28 and 1 or -1))
            data = struct.pack('<h', max(-32768, min(32767, value)))
            wav_file.writeframesraw(data)
            
    return wav_io.getvalue()


def main():
    print("=" * 60)
    print("🚀 AntiGravity — OmniVoice Cloud API End-to-End Test")
    print("=" * 60)
    print(f"Target Gateway: {API_BASE_URL}")

    headers = {"X-API-Key": API_KEY}

    # Step 1: Health Check
    print("\n[1/4] Checking System Health (/health)...")
    try:
        resp = requests.get(f"{API_BASE_URL}/health", timeout=10)
        print(f"Health Response [{resp.status_code}]:")
        print(resp.json())
        if resp.status_code != 200:
            print("❌ Health check failed!")
            sys.exit(1)
    except Exception as e:
        print(f"❌ Connection error: {e}")
        sys.exit(1)

    # Step 2: Upload Reference Audio
    print("\n[2/4] Uploading Reference Audio Sample (/api/reference)...")
    sample_wav = create_sample_wav_bytes()
    files = {"file": ("test_reference.wav", sample_wav, "audio/wav")}

    upload_resp = requests.post(
        f"{API_BASE_URL}/api/reference",
        headers=headers,
        files=files,
        timeout=30
    )
    print(f"Upload Response [{upload_resp.status_code}]:")
    print(upload_resp.json())

    if upload_resp.status_code != 200:
        print("❌ Reference upload failed!")
        sys.exit(1)

    ref_data = upload_resp.json()
    ref_id = ref_data["reference_id"]
    print(f"✅ Received Reference ID: {ref_id}")

    # Step 3: Trigger Voice Cloning TTS Synthesis
    print("\n[3/4] Requesting Voice Synthesis (/api/tts)...")
    tts_payload = {
        "text": "Hello! This is a test speech synthesis generated by OmniVoice Cloud API on RunPod GPUs.",
        "reference_id": ref_id,
        "speed": 1.0,
        "temperature": 0.7
    }

    tts_resp = requests.post(
        f"{API_BASE_URL}/api/tts",
        headers=headers,
        json=tts_payload,
        timeout=300
    )

    print(f"TTS Response [{tts_resp.status_code}]:")
    print(tts_resp.json())

    if tts_resp.status_code != 200:
        print("❌ Speech synthesis failed!")
        sys.exit(1)

    job_data = tts_resp.json()
    download_url = job_data.get("download_url")
    print(f"✅ Generated Audio Download Presigned URL:\n{download_url}")

    # Step 4: Verify Output Audio Download
    print("\n[4/4] Verifying Audio Download...")
    if download_url:
        try:
            audio_get = requests.get(download_url, timeout=30)
            print(f"Downloaded Audio Size: {len(audio_get.content)} bytes (Status: {audio_get.status_code})")
            out_filename = "omnivoice_test_output.wav"
            with open(out_filename, "wb") as f:
                f.write(audio_get.content)
            print(f"🎉 Saved output audio to '{out_filename}'")
        except Exception as e:
            print(f"⚠️ Could not download from presigned URL directly: {e}")

    print("\n" + "=" * 60)
    print("✅ All test steps completed successfully!")
    print("=" * 60)


if __name__ == "__main__":
    main()
